name: "Olaf's Blog"
favicon: null
layout_spectrum: 0.9404401879291981
typography_spectrum: 0.6718715142924339
title: "Olaf's Homepage"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1fabfa'
    - '#000000'
    - '#f90612'
    - '#ffffff'
    - '#585858'
  brandStrength: 0.15526145254261792
  lightness: 0.2200359480921179
  saturation: 0.6832527529913932
  rhythmicContrast: 0.9569926792755723
purpose: []
